name: Publish and Release

on:
  push:
    branches: [main]
    paths: ["package.json", ".github/workflows/**"]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml

  publish_github_package:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-files
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com'
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    needs: [build-and-test, publish_github_package]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ needs.build-and-test.outputs.version }}
          name: ${{ needs.build-and-test.outputs.name }} v${{ needs.build-and-test.outputs.version }}
          allowUpdates: true
          generateReleaseNotes: true
          skipIfReleaseExists: true
